name: Nightly
on:
  schedule:
    - cron: 0 8 * * 1-5
  workflow_dispatch: {}

jobs:
  trunk_check:
    name: Trunk Check Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@782e83f803ca6e369f035d64c6ba2768174ba61b
        with:
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
